namespace V_Mart
{
    partial class AdminUpdateProduct
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminUpdateProduct));
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.btn_UpdateImg = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Input_ProductCategory = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_BioInfo = new Bunifu.UI.WinForms.BunifuLabel();
            this.Input_ProductName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btn_UpdateCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Input_Details = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_UpdateDetail = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Input_Price = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_UpdateName = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_UpdatePrice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Input_ProductId = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuShadowPanel3.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.BorderRadius = 10;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel2.Controls.Add(this.Input_ProductId);
            this.bunifuShadowPanel2.Controls.Add(this.btn_UpdateName);
            this.bunifuShadowPanel2.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel2.Controls.Add(this.btn_UpdateImg);
            this.bunifuShadowPanel2.Controls.Add(this.lbl_BioInfo);
            this.bunifuShadowPanel2.Controls.Add(this.Input_ProductName);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(3, 3);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 2;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(513, 191);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 15;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(331, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(165, 116);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 31;
            this.pictureBox1.TabStop = false;
            // 
            // btn_UpdateImg
            // 
            this.btn_UpdateImg.AllowAnimations = true;
            this.btn_UpdateImg.AllowMouseEffects = true;
            this.btn_UpdateImg.AllowToggling = false;
            this.btn_UpdateImg.AnimationSpeed = 200;
            this.btn_UpdateImg.AutoGenerateColors = false;
            this.btn_UpdateImg.AutoRoundBorders = false;
            this.btn_UpdateImg.AutoSizeLeftIcon = true;
            this.btn_UpdateImg.AutoSizeRightIcon = true;
            this.btn_UpdateImg.BackColor = System.Drawing.Color.Transparent;
            this.btn_UpdateImg.BackColor1 = System.Drawing.Color.LightSlateGray;
            this.btn_UpdateImg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UpdateImg.BackgroundImage")));
            this.btn_UpdateImg.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateImg.ButtonText = "Update Image";
            this.btn_UpdateImg.ButtonTextMarginLeft = 0;
            this.btn_UpdateImg.ColorContrastOnClick = 45;
            this.btn_UpdateImg.ColorContrastOnHover = 45;
            this.btn_UpdateImg.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_UpdateImg.CustomizableEdges = borderEdges2;
            this.btn_UpdateImg.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UpdateImg.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateImg.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateImg.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateImg.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UpdateImg.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_UpdateImg.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateImg.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_UpdateImg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateImg.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_UpdateImg.IconMarginLeft = 11;
            this.btn_UpdateImg.IconPadding = 10;
            this.btn_UpdateImg.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_UpdateImg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateImg.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_UpdateImg.IconSize = 25;
            this.btn_UpdateImg.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateImg.IdleBorderRadius = 15;
            this.btn_UpdateImg.IdleBorderThickness = 2;
            this.btn_UpdateImg.IdleFillColor = System.Drawing.Color.LightSlateGray;
            this.btn_UpdateImg.IdleIconLeftImage = null;
            this.btn_UpdateImg.IdleIconRightImage = null;
            this.btn_UpdateImg.IndicateFocus = false;
            this.btn_UpdateImg.Location = new System.Drawing.Point(355, 139);
            this.btn_UpdateImg.Name = "btn_UpdateImg";
            this.btn_UpdateImg.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateImg.OnDisabledState.BorderRadius = 15;
            this.btn_UpdateImg.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateImg.OnDisabledState.BorderThickness = 2;
            this.btn_UpdateImg.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateImg.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateImg.OnDisabledState.IconLeftImage = null;
            this.btn_UpdateImg.OnDisabledState.IconRightImage = null;
            this.btn_UpdateImg.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateImg.onHoverState.BorderRadius = 15;
            this.btn_UpdateImg.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateImg.onHoverState.BorderThickness = 2;
            this.btn_UpdateImg.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateImg.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateImg.onHoverState.IconLeftImage = null;
            this.btn_UpdateImg.onHoverState.IconRightImage = null;
            this.btn_UpdateImg.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateImg.OnIdleState.BorderRadius = 15;
            this.btn_UpdateImg.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateImg.OnIdleState.BorderThickness = 2;
            this.btn_UpdateImg.OnIdleState.FillColor = System.Drawing.Color.LightSlateGray;
            this.btn_UpdateImg.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateImg.OnIdleState.IconLeftImage = null;
            this.btn_UpdateImg.OnIdleState.IconRightImage = null;
            this.btn_UpdateImg.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateImg.OnPressedState.BorderRadius = 15;
            this.btn_UpdateImg.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateImg.OnPressedState.BorderThickness = 2;
            this.btn_UpdateImg.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateImg.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateImg.OnPressedState.IconLeftImage = null;
            this.btn_UpdateImg.OnPressedState.IconRightImage = null;
            this.btn_UpdateImg.Size = new System.Drawing.Size(112, 31);
            this.btn_UpdateImg.TabIndex = 29;
            this.btn_UpdateImg.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UpdateImg.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_UpdateImg.TextMarginLeft = 0;
            this.btn_UpdateImg.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_UpdateImg.UseDefaultRadiusAndThickness = true;
            this.btn_UpdateImg.Click += new System.EventHandler(this.btn_UpdateImg_Click);
            // 
            // Input_ProductCategory
            // 
            this.Input_ProductCategory.AcceptsReturn = false;
            this.Input_ProductCategory.AcceptsTab = false;
            this.Input_ProductCategory.AnimationSpeed = 200;
            this.Input_ProductCategory.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_ProductCategory.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_ProductCategory.BackColor = System.Drawing.Color.Transparent;
            this.Input_ProductCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_ProductCategory.BackgroundImage")));
            this.Input_ProductCategory.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_ProductCategory.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_ProductCategory.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_ProductCategory.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_ProductCategory.BorderRadius = 6;
            this.Input_ProductCategory.BorderThickness = 1;
            this.Input_ProductCategory.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_ProductCategory.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductCategory.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_ProductCategory.DefaultText = "";
            this.Input_ProductCategory.FillColor = System.Drawing.Color.White;
            this.Input_ProductCategory.HideSelection = true;
            this.Input_ProductCategory.IconLeft = null;
            this.Input_ProductCategory.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductCategory.IconPadding = 10;
            this.Input_ProductCategory.IconRight = null;
            this.Input_ProductCategory.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductCategory.Lines = new string[0];
            this.Input_ProductCategory.Location = new System.Drawing.Point(28, 154);
            this.Input_ProductCategory.Margin = new System.Windows.Forms.Padding(2);
            this.Input_ProductCategory.MaxLength = 32767;
            this.Input_ProductCategory.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_ProductCategory.Modified = false;
            this.Input_ProductCategory.Multiline = false;
            this.Input_ProductCategory.Name = "Input_ProductCategory";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductCategory.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_ProductCategory.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductCategory.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductCategory.OnIdleState = stateProperties12;
            this.Input_ProductCategory.Padding = new System.Windows.Forms.Padding(2);
            this.Input_ProductCategory.PasswordChar = '\0';
            this.Input_ProductCategory.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_ProductCategory.PlaceholderText = "Category";
            this.Input_ProductCategory.ReadOnly = false;
            this.Input_ProductCategory.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_ProductCategory.SelectedText = "";
            this.Input_ProductCategory.SelectionLength = 0;
            this.Input_ProductCategory.SelectionStart = 0;
            this.Input_ProductCategory.ShortcutsEnabled = true;
            this.Input_ProductCategory.Size = new System.Drawing.Size(367, 34);
            this.Input_ProductCategory.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_ProductCategory.TabIndex = 2;
            this.Input_ProductCategory.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_ProductCategory.TextMarginBottom = 0;
            this.Input_ProductCategory.TextMarginLeft = 3;
            this.Input_ProductCategory.TextMarginTop = 0;
            this.Input_ProductCategory.TextPlaceholder = "Category";
            this.Input_ProductCategory.UseSystemPasswordChar = false;
            this.Input_ProductCategory.WordWrap = true;
            // 
            // lbl_BioInfo
            // 
            this.lbl_BioInfo.AllowParentOverrides = false;
            this.lbl_BioInfo.AutoEllipsis = false;
            this.lbl_BioInfo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_BioInfo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_BioInfo.Font = new System.Drawing.Font("Ebrima", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_BioInfo.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.lbl_BioInfo.Location = new System.Drawing.Point(32, 17);
            this.lbl_BioInfo.Name = "lbl_BioInfo";
            this.lbl_BioInfo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_BioInfo.Size = new System.Drawing.Size(144, 20);
            this.lbl_BioInfo.TabIndex = 1;
            this.lbl_BioInfo.Text = "Product Information";
            this.lbl_BioInfo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_BioInfo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Input_ProductName
            // 
            this.Input_ProductName.AcceptsReturn = false;
            this.Input_ProductName.AcceptsTab = false;
            this.Input_ProductName.AnimationSpeed = 200;
            this.Input_ProductName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_ProductName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_ProductName.BackColor = System.Drawing.Color.Transparent;
            this.Input_ProductName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_ProductName.BackgroundImage")));
            this.Input_ProductName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_ProductName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_ProductName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_ProductName.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_ProductName.BorderRadius = 6;
            this.Input_ProductName.BorderThickness = 1;
            this.Input_ProductName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_ProductName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_ProductName.DefaultText = "";
            this.Input_ProductName.FillColor = System.Drawing.Color.White;
            this.Input_ProductName.HideSelection = true;
            this.Input_ProductName.IconLeft = null;
            this.Input_ProductName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductName.IconPadding = 10;
            this.Input_ProductName.IconRight = null;
            this.Input_ProductName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductName.Lines = new string[0];
            this.Input_ProductName.Location = new System.Drawing.Point(28, 94);
            this.Input_ProductName.Margin = new System.Windows.Forms.Padding(2);
            this.Input_ProductName.MaxLength = 32767;
            this.Input_ProductName.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_ProductName.Modified = false;
            this.Input_ProductName.Multiline = false;
            this.Input_ProductName.Name = "Input_ProductName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_ProductName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductName.OnIdleState = stateProperties8;
            this.Input_ProductName.Padding = new System.Windows.Forms.Padding(2);
            this.Input_ProductName.PasswordChar = '\0';
            this.Input_ProductName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_ProductName.PlaceholderText = "Product Name";
            this.Input_ProductName.ReadOnly = false;
            this.Input_ProductName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_ProductName.SelectedText = "";
            this.Input_ProductName.SelectionLength = 0;
            this.Input_ProductName.SelectionStart = 0;
            this.Input_ProductName.ShortcutsEnabled = true;
            this.Input_ProductName.Size = new System.Drawing.Size(229, 34);
            this.Input_ProductName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_ProductName.TabIndex = 0;
            this.Input_ProductName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_ProductName.TextMarginBottom = 0;
            this.Input_ProductName.TextMarginLeft = 3;
            this.Input_ProductName.TextMarginTop = 0;
            this.Input_ProductName.TextPlaceholder = "Product Name";
            this.Input_ProductName.UseSystemPasswordChar = false;
            this.Input_ProductName.WordWrap = true;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.BorderRadius = 10;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuShadowPanel3.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(3, 3);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 2;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(519, 465);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 53;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 10;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.btn_UpdatePrice);
            this.bunifuShadowPanel1.Controls.Add(this.btn_UpdateDetail);
            this.bunifuShadowPanel1.Controls.Add(this.btn_UpdateCategory);
            this.bunifuShadowPanel1.Controls.Add(this.Input_Price);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.Input_Details);
            this.bunifuShadowPanel1.Controls.Add(this.Input_ProductCategory);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(3, 200);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 2;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(513, 262);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 16;
            // 
            // btn_UpdateCategory
            // 
            this.btn_UpdateCategory.AllowAnimations = true;
            this.btn_UpdateCategory.AllowMouseEffects = true;
            this.btn_UpdateCategory.AllowToggling = false;
            this.btn_UpdateCategory.AnimationSpeed = 200;
            this.btn_UpdateCategory.AutoGenerateColors = false;
            this.btn_UpdateCategory.AutoRoundBorders = false;
            this.btn_UpdateCategory.AutoSizeLeftIcon = true;
            this.btn_UpdateCategory.AutoSizeRightIcon = true;
            this.btn_UpdateCategory.BackColor = System.Drawing.Color.Transparent;
            this.btn_UpdateCategory.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UpdateCategory.BackgroundImage")));
            this.btn_UpdateCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateCategory.ButtonText = "Update Category";
            this.btn_UpdateCategory.ButtonTextMarginLeft = 0;
            this.btn_UpdateCategory.ColorContrastOnClick = 45;
            this.btn_UpdateCategory.ColorContrastOnHover = 45;
            this.btn_UpdateCategory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_UpdateCategory.CustomizableEdges = borderEdges5;
            this.btn_UpdateCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UpdateCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateCategory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateCategory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UpdateCategory.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_UpdateCategory.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_UpdateCategory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_UpdateCategory.IconMarginLeft = 11;
            this.btn_UpdateCategory.IconPadding = 10;
            this.btn_UpdateCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_UpdateCategory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_UpdateCategory.IconSize = 25;
            this.btn_UpdateCategory.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateCategory.IdleBorderRadius = 15;
            this.btn_UpdateCategory.IdleBorderThickness = 2;
            this.btn_UpdateCategory.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateCategory.IdleIconLeftImage = null;
            this.btn_UpdateCategory.IdleIconRightImage = null;
            this.btn_UpdateCategory.IndicateFocus = false;
            this.btn_UpdateCategory.Location = new System.Drawing.Point(400, 154);
            this.btn_UpdateCategory.Name = "btn_UpdateCategory";
            this.btn_UpdateCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateCategory.OnDisabledState.BorderRadius = 15;
            this.btn_UpdateCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateCategory.OnDisabledState.BorderThickness = 2;
            this.btn_UpdateCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateCategory.OnDisabledState.IconLeftImage = null;
            this.btn_UpdateCategory.OnDisabledState.IconRightImage = null;
            this.btn_UpdateCategory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateCategory.onHoverState.BorderRadius = 15;
            this.btn_UpdateCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateCategory.onHoverState.BorderThickness = 2;
            this.btn_UpdateCategory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateCategory.onHoverState.IconLeftImage = null;
            this.btn_UpdateCategory.onHoverState.IconRightImage = null;
            this.btn_UpdateCategory.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateCategory.OnIdleState.BorderRadius = 15;
            this.btn_UpdateCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateCategory.OnIdleState.BorderThickness = 2;
            this.btn_UpdateCategory.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateCategory.OnIdleState.IconLeftImage = null;
            this.btn_UpdateCategory.OnIdleState.IconRightImage = null;
            this.btn_UpdateCategory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateCategory.OnPressedState.BorderRadius = 15;
            this.btn_UpdateCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateCategory.OnPressedState.BorderThickness = 2;
            this.btn_UpdateCategory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateCategory.OnPressedState.IconLeftImage = null;
            this.btn_UpdateCategory.OnPressedState.IconRightImage = null;
            this.btn_UpdateCategory.Size = new System.Drawing.Size(103, 34);
            this.btn_UpdateCategory.TabIndex = 28;
            this.btn_UpdateCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UpdateCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_UpdateCategory.TextMarginLeft = 0;
            this.btn_UpdateCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_UpdateCategory.UseDefaultRadiusAndThickness = true;
            this.btn_UpdateCategory.Click += new System.EventHandler(this.btn_UpdateCategory_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Ebrima", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.bunifuLabel1.Location = new System.Drawing.Point(28, 19);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(139, 20);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Product Description";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Input_Details
            // 
            this.Input_Details.AcceptsReturn = false;
            this.Input_Details.AcceptsTab = false;
            this.Input_Details.AnimationSpeed = 200;
            this.Input_Details.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Details.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Details.BackColor = System.Drawing.Color.Transparent;
            this.Input_Details.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Details.BackgroundImage")));
            this.Input_Details.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Details.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Details.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Details.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Details.BorderRadius = 6;
            this.Input_Details.BorderThickness = 1;
            this.Input_Details.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Details.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Details.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Details.DefaultText = "";
            this.Input_Details.FillColor = System.Drawing.Color.White;
            this.Input_Details.HideSelection = true;
            this.Input_Details.IconLeft = null;
            this.Input_Details.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Details.IconPadding = 10;
            this.Input_Details.IconRight = null;
            this.Input_Details.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Details.Lines = new string[0];
            this.Input_Details.Location = new System.Drawing.Point(28, 59);
            this.Input_Details.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Details.MaxLength = 32767;
            this.Input_Details.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Details.Modified = false;
            this.Input_Details.Multiline = true;
            this.Input_Details.Name = "Input_Details";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Details.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Details.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Details.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Details.OnIdleState = stateProperties20;
            this.Input_Details.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Details.PasswordChar = '\0';
            this.Input_Details.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Details.PlaceholderText = "Product Description... Write here";
            this.Input_Details.ReadOnly = false;
            this.Input_Details.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Details.SelectedText = "";
            this.Input_Details.SelectionLength = 0;
            this.Input_Details.SelectionStart = 0;
            this.Input_Details.ShortcutsEnabled = true;
            this.Input_Details.Size = new System.Drawing.Size(367, 79);
            this.Input_Details.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Details.TabIndex = 0;
            this.Input_Details.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Details.TextMarginBottom = 0;
            this.Input_Details.TextMarginLeft = 3;
            this.Input_Details.TextMarginTop = 0;
            this.Input_Details.TextPlaceholder = "Product Description... Write here";
            this.Input_Details.UseSystemPasswordChar = false;
            this.Input_Details.WordWrap = true;
            // 
            // btn_UpdateDetail
            // 
            this.btn_UpdateDetail.AllowAnimations = true;
            this.btn_UpdateDetail.AllowMouseEffects = true;
            this.btn_UpdateDetail.AllowToggling = false;
            this.btn_UpdateDetail.AnimationSpeed = 200;
            this.btn_UpdateDetail.AutoGenerateColors = false;
            this.btn_UpdateDetail.AutoRoundBorders = false;
            this.btn_UpdateDetail.AutoSizeLeftIcon = true;
            this.btn_UpdateDetail.AutoSizeRightIcon = true;
            this.btn_UpdateDetail.BackColor = System.Drawing.Color.Transparent;
            this.btn_UpdateDetail.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateDetail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UpdateDetail.BackgroundImage")));
            this.btn_UpdateDetail.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateDetail.ButtonText = "Update Detail";
            this.btn_UpdateDetail.ButtonTextMarginLeft = 0;
            this.btn_UpdateDetail.ColorContrastOnClick = 45;
            this.btn_UpdateDetail.ColorContrastOnHover = 45;
            this.btn_UpdateDetail.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_UpdateDetail.CustomizableEdges = borderEdges4;
            this.btn_UpdateDetail.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UpdateDetail.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateDetail.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateDetail.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateDetail.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UpdateDetail.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_UpdateDetail.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateDetail.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_UpdateDetail.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateDetail.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_UpdateDetail.IconMarginLeft = 11;
            this.btn_UpdateDetail.IconPadding = 10;
            this.btn_UpdateDetail.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_UpdateDetail.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateDetail.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_UpdateDetail.IconSize = 25;
            this.btn_UpdateDetail.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateDetail.IdleBorderRadius = 15;
            this.btn_UpdateDetail.IdleBorderThickness = 2;
            this.btn_UpdateDetail.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateDetail.IdleIconLeftImage = null;
            this.btn_UpdateDetail.IdleIconRightImage = null;
            this.btn_UpdateDetail.IndicateFocus = false;
            this.btn_UpdateDetail.Location = new System.Drawing.Point(400, 82);
            this.btn_UpdateDetail.Name = "btn_UpdateDetail";
            this.btn_UpdateDetail.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateDetail.OnDisabledState.BorderRadius = 15;
            this.btn_UpdateDetail.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateDetail.OnDisabledState.BorderThickness = 2;
            this.btn_UpdateDetail.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateDetail.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateDetail.OnDisabledState.IconLeftImage = null;
            this.btn_UpdateDetail.OnDisabledState.IconRightImage = null;
            this.btn_UpdateDetail.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateDetail.onHoverState.BorderRadius = 15;
            this.btn_UpdateDetail.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateDetail.onHoverState.BorderThickness = 2;
            this.btn_UpdateDetail.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateDetail.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateDetail.onHoverState.IconLeftImage = null;
            this.btn_UpdateDetail.onHoverState.IconRightImage = null;
            this.btn_UpdateDetail.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateDetail.OnIdleState.BorderRadius = 15;
            this.btn_UpdateDetail.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateDetail.OnIdleState.BorderThickness = 2;
            this.btn_UpdateDetail.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateDetail.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateDetail.OnIdleState.IconLeftImage = null;
            this.btn_UpdateDetail.OnIdleState.IconRightImage = null;
            this.btn_UpdateDetail.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateDetail.OnPressedState.BorderRadius = 15;
            this.btn_UpdateDetail.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateDetail.OnPressedState.BorderThickness = 2;
            this.btn_UpdateDetail.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateDetail.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateDetail.OnPressedState.IconLeftImage = null;
            this.btn_UpdateDetail.OnPressedState.IconRightImage = null;
            this.btn_UpdateDetail.Size = new System.Drawing.Size(103, 36);
            this.btn_UpdateDetail.TabIndex = 29;
            this.btn_UpdateDetail.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UpdateDetail.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_UpdateDetail.TextMarginLeft = 0;
            this.btn_UpdateDetail.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_UpdateDetail.UseDefaultRadiusAndThickness = true;
            this.btn_UpdateDetail.Click += new System.EventHandler(this.btn_UpdateDetail_Click);
            // 
            // Input_Price
            // 
            this.Input_Price.AcceptsReturn = false;
            this.Input_Price.AcceptsTab = false;
            this.Input_Price.AnimationSpeed = 200;
            this.Input_Price.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Price.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Price.BackColor = System.Drawing.Color.Transparent;
            this.Input_Price.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Price.BackgroundImage")));
            this.Input_Price.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Price.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Price.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Price.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Price.BorderRadius = 6;
            this.Input_Price.BorderThickness = 1;
            this.Input_Price.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Price.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Price.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Price.DefaultText = "";
            this.Input_Price.FillColor = System.Drawing.Color.White;
            this.Input_Price.HideSelection = true;
            this.Input_Price.IconLeft = null;
            this.Input_Price.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Price.IconPadding = 10;
            this.Input_Price.IconRight = null;
            this.Input_Price.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Price.Lines = new string[0];
            this.Input_Price.Location = new System.Drawing.Point(28, 203);
            this.Input_Price.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Price.MaxLength = 32767;
            this.Input_Price.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Price.Modified = false;
            this.Input_Price.Multiline = false;
            this.Input_Price.Name = "Input_Price";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Price.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Price.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Price.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Price.OnIdleState = stateProperties16;
            this.Input_Price.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Price.PasswordChar = '\0';
            this.Input_Price.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Price.PlaceholderText = "Price";
            this.Input_Price.ReadOnly = false;
            this.Input_Price.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Price.SelectedText = "";
            this.Input_Price.SelectionLength = 0;
            this.Input_Price.SelectionStart = 0;
            this.Input_Price.ShortcutsEnabled = true;
            this.Input_Price.Size = new System.Drawing.Size(110, 34);
            this.Input_Price.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Price.TabIndex = 32;
            this.Input_Price.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Price.TextMarginBottom = 0;
            this.Input_Price.TextMarginLeft = 3;
            this.Input_Price.TextMarginTop = 0;
            this.Input_Price.TextPlaceholder = "Price";
            this.Input_Price.UseSystemPasswordChar = false;
            this.Input_Price.WordWrap = true;
            // 
            // btn_UpdateName
            // 
            this.btn_UpdateName.AllowAnimations = true;
            this.btn_UpdateName.AllowMouseEffects = true;
            this.btn_UpdateName.AllowToggling = false;
            this.btn_UpdateName.AnimationSpeed = 200;
            this.btn_UpdateName.AutoGenerateColors = false;
            this.btn_UpdateName.AutoRoundBorders = false;
            this.btn_UpdateName.AutoSizeLeftIcon = true;
            this.btn_UpdateName.AutoSizeRightIcon = true;
            this.btn_UpdateName.BackColor = System.Drawing.Color.Transparent;
            this.btn_UpdateName.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UpdateName.BackgroundImage")));
            this.btn_UpdateName.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateName.ButtonText = "Update Name";
            this.btn_UpdateName.ButtonTextMarginLeft = 0;
            this.btn_UpdateName.ColorContrastOnClick = 45;
            this.btn_UpdateName.ColorContrastOnHover = 45;
            this.btn_UpdateName.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_UpdateName.CustomizableEdges = borderEdges1;
            this.btn_UpdateName.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UpdateName.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateName.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateName.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateName.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UpdateName.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_UpdateName.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateName.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_UpdateName.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateName.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_UpdateName.IconMarginLeft = 11;
            this.btn_UpdateName.IconPadding = 10;
            this.btn_UpdateName.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_UpdateName.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdateName.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_UpdateName.IconSize = 25;
            this.btn_UpdateName.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateName.IdleBorderRadius = 15;
            this.btn_UpdateName.IdleBorderThickness = 2;
            this.btn_UpdateName.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateName.IdleIconLeftImage = null;
            this.btn_UpdateName.IdleIconRightImage = null;
            this.btn_UpdateName.IndicateFocus = false;
            this.btn_UpdateName.Location = new System.Drawing.Point(154, 136);
            this.btn_UpdateName.Name = "btn_UpdateName";
            this.btn_UpdateName.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdateName.OnDisabledState.BorderRadius = 15;
            this.btn_UpdateName.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateName.OnDisabledState.BorderThickness = 2;
            this.btn_UpdateName.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdateName.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdateName.OnDisabledState.IconLeftImage = null;
            this.btn_UpdateName.OnDisabledState.IconRightImage = null;
            this.btn_UpdateName.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateName.onHoverState.BorderRadius = 15;
            this.btn_UpdateName.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateName.onHoverState.BorderThickness = 2;
            this.btn_UpdateName.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdateName.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateName.onHoverState.IconLeftImage = null;
            this.btn_UpdateName.onHoverState.IconRightImage = null;
            this.btn_UpdateName.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdateName.OnIdleState.BorderRadius = 15;
            this.btn_UpdateName.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateName.OnIdleState.BorderThickness = 2;
            this.btn_UpdateName.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdateName.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateName.OnIdleState.IconLeftImage = null;
            this.btn_UpdateName.OnIdleState.IconRightImage = null;
            this.btn_UpdateName.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateName.OnPressedState.BorderRadius = 15;
            this.btn_UpdateName.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdateName.OnPressedState.BorderThickness = 2;
            this.btn_UpdateName.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdateName.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdateName.OnPressedState.IconLeftImage = null;
            this.btn_UpdateName.OnPressedState.IconRightImage = null;
            this.btn_UpdateName.Size = new System.Drawing.Size(103, 34);
            this.btn_UpdateName.TabIndex = 33;
            this.btn_UpdateName.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UpdateName.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_UpdateName.TextMarginLeft = 0;
            this.btn_UpdateName.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_UpdateName.UseDefaultRadiusAndThickness = true;
            this.btn_UpdateName.Click += new System.EventHandler(this.btn_UpdateName_Click);
            // 
            // btn_UpdatePrice
            // 
            this.btn_UpdatePrice.AllowAnimations = true;
            this.btn_UpdatePrice.AllowMouseEffects = true;
            this.btn_UpdatePrice.AllowToggling = false;
            this.btn_UpdatePrice.AnimationSpeed = 200;
            this.btn_UpdatePrice.AutoGenerateColors = false;
            this.btn_UpdatePrice.AutoRoundBorders = false;
            this.btn_UpdatePrice.AutoSizeLeftIcon = true;
            this.btn_UpdatePrice.AutoSizeRightIcon = true;
            this.btn_UpdatePrice.BackColor = System.Drawing.Color.Transparent;
            this.btn_UpdatePrice.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btn_UpdatePrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UpdatePrice.BackgroundImage")));
            this.btn_UpdatePrice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdatePrice.ButtonText = "Update Price";
            this.btn_UpdatePrice.ButtonTextMarginLeft = 0;
            this.btn_UpdatePrice.ColorContrastOnClick = 45;
            this.btn_UpdatePrice.ColorContrastOnHover = 45;
            this.btn_UpdatePrice.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_UpdatePrice.CustomizableEdges = borderEdges3;
            this.btn_UpdatePrice.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UpdatePrice.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdatePrice.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdatePrice.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdatePrice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UpdatePrice.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_UpdatePrice.ForeColor = System.Drawing.Color.White;
            this.btn_UpdatePrice.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_UpdatePrice.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdatePrice.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_UpdatePrice.IconMarginLeft = 11;
            this.btn_UpdatePrice.IconPadding = 10;
            this.btn_UpdatePrice.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_UpdatePrice.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_UpdatePrice.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_UpdatePrice.IconSize = 25;
            this.btn_UpdatePrice.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdatePrice.IdleBorderRadius = 15;
            this.btn_UpdatePrice.IdleBorderThickness = 2;
            this.btn_UpdatePrice.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdatePrice.IdleIconLeftImage = null;
            this.btn_UpdatePrice.IdleIconRightImage = null;
            this.btn_UpdatePrice.IndicateFocus = false;
            this.btn_UpdatePrice.Location = new System.Drawing.Point(154, 203);
            this.btn_UpdatePrice.Name = "btn_UpdatePrice";
            this.btn_UpdatePrice.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_UpdatePrice.OnDisabledState.BorderRadius = 15;
            this.btn_UpdatePrice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdatePrice.OnDisabledState.BorderThickness = 2;
            this.btn_UpdatePrice.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UpdatePrice.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UpdatePrice.OnDisabledState.IconLeftImage = null;
            this.btn_UpdatePrice.OnDisabledState.IconRightImage = null;
            this.btn_UpdatePrice.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdatePrice.onHoverState.BorderRadius = 15;
            this.btn_UpdatePrice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdatePrice.onHoverState.BorderThickness = 2;
            this.btn_UpdatePrice.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_UpdatePrice.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdatePrice.onHoverState.IconLeftImage = null;
            this.btn_UpdatePrice.onHoverState.IconRightImage = null;
            this.btn_UpdatePrice.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_UpdatePrice.OnIdleState.BorderRadius = 15;
            this.btn_UpdatePrice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdatePrice.OnIdleState.BorderThickness = 2;
            this.btn_UpdatePrice.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btn_UpdatePrice.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdatePrice.OnIdleState.IconLeftImage = null;
            this.btn_UpdatePrice.OnIdleState.IconRightImage = null;
            this.btn_UpdatePrice.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdatePrice.OnPressedState.BorderRadius = 15;
            this.btn_UpdatePrice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UpdatePrice.OnPressedState.BorderThickness = 2;
            this.btn_UpdatePrice.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_UpdatePrice.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_UpdatePrice.OnPressedState.IconLeftImage = null;
            this.btn_UpdatePrice.OnPressedState.IconRightImage = null;
            this.btn_UpdatePrice.Size = new System.Drawing.Size(103, 34);
            this.btn_UpdatePrice.TabIndex = 33;
            this.btn_UpdatePrice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UpdatePrice.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_UpdatePrice.TextMarginLeft = 0;
            this.btn_UpdatePrice.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_UpdatePrice.UseDefaultRadiusAndThickness = true;
            this.btn_UpdatePrice.Click += new System.EventHandler(this.btn_UpdatePrice_Click);
            // 
            // Input_ProductId
            // 
            this.Input_ProductId.AcceptsReturn = false;
            this.Input_ProductId.AcceptsTab = false;
            this.Input_ProductId.AnimationSpeed = 200;
            this.Input_ProductId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_ProductId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_ProductId.BackColor = System.Drawing.Color.Transparent;
            this.Input_ProductId.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_ProductId.BackgroundImage")));
            this.Input_ProductId.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_ProductId.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_ProductId.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_ProductId.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_ProductId.BorderRadius = 6;
            this.Input_ProductId.BorderThickness = 1;
            this.Input_ProductId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_ProductId.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductId.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_ProductId.DefaultText = "";
            this.Input_ProductId.FillColor = System.Drawing.Color.White;
            this.Input_ProductId.HideSelection = true;
            this.Input_ProductId.IconLeft = null;
            this.Input_ProductId.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductId.IconPadding = 10;
            this.Input_ProductId.IconRight = null;
            this.Input_ProductId.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductId.Lines = new string[0];
            this.Input_ProductId.Location = new System.Drawing.Point(29, 55);
            this.Input_ProductId.Margin = new System.Windows.Forms.Padding(2);
            this.Input_ProductId.MaxLength = 32767;
            this.Input_ProductId.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_ProductId.Modified = false;
            this.Input_ProductId.Multiline = false;
            this.Input_ProductId.Name = "Input_ProductId";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductId.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_ProductId.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductId.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductId.OnIdleState = stateProperties4;
            this.Input_ProductId.Padding = new System.Windows.Forms.Padding(2);
            this.Input_ProductId.PasswordChar = '\0';
            this.Input_ProductId.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_ProductId.PlaceholderText = "Product Id";
            this.Input_ProductId.ReadOnly = false;
            this.Input_ProductId.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_ProductId.SelectedText = "";
            this.Input_ProductId.SelectionLength = 0;
            this.Input_ProductId.SelectionStart = 0;
            this.Input_ProductId.ShortcutsEnabled = true;
            this.Input_ProductId.Size = new System.Drawing.Size(138, 34);
            this.Input_ProductId.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_ProductId.TabIndex = 34;
            this.Input_ProductId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_ProductId.TextMarginBottom = 0;
            this.Input_ProductId.TextMarginLeft = 3;
            this.Input_ProductId.TextMarginTop = 0;
            this.Input_ProductId.TextPlaceholder = "Product Id";
            this.Input_ProductId.UseSystemPasswordChar = false;
            this.Input_ProductId.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Ebrima", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Crimson;
            this.bunifuLabel2.Location = new System.Drawing.Point(172, 55);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(7, 20);
            this.bunifuLabel2.TabIndex = 35;
            this.bunifuLabel2.Text = "*";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AdminUpdateProduct
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuShadowPanel3);
            this.Name = "AdminUpdateProduct";
            this.Size = new System.Drawing.Size(525, 471);
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UpdateImg;
        private Bunifu.UI.WinForms.BunifuTextBox Input_ProductCategory;
        private Bunifu.UI.WinForms.BunifuLabel lbl_BioInfo;
        private Bunifu.UI.WinForms.BunifuTextBox Input_ProductName;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UpdateCategory;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Details;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UpdateName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UpdatePrice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UpdateDetail;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Price;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox Input_ProductId;
    }
}
