namespace V_Mart
{
    partial class AdminAddProduct
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminAddProduct));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.Input_Stock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Input_ProductCategory = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_BioInfo = new Bunifu.UI.WinForms.BunifuLabel();
            this.Input_ProductName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Input_Details = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_AddProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_ImgUpload = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Input_Price = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuShadowPanel3.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.BorderRadius = 10;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuShadowPanel3.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(3, 3);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 2;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(519, 465);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 52;
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.BorderRadius = 10;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel2.Controls.Add(this.Input_Price);
            this.bunifuShadowPanel2.Controls.Add(this.btn_ImgUpload);
            this.bunifuShadowPanel2.Controls.Add(this.Input_Stock);
            this.bunifuShadowPanel2.Controls.Add(this.Input_ProductCategory);
            this.bunifuShadowPanel2.Controls.Add(this.lbl_BioInfo);
            this.bunifuShadowPanel2.Controls.Add(this.Input_ProductName);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(3, 3);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 2;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(513, 191);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 15;
            // 
            // Input_Stock
            // 
            this.Input_Stock.AcceptsReturn = false;
            this.Input_Stock.AcceptsTab = false;
            this.Input_Stock.AnimationSpeed = 200;
            this.Input_Stock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Stock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Stock.BackColor = System.Drawing.Color.Transparent;
            this.Input_Stock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Stock.BackgroundImage")));
            this.Input_Stock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Stock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Stock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Stock.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Stock.BorderRadius = 6;
            this.Input_Stock.BorderThickness = 1;
            this.Input_Stock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Stock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Stock.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Stock.DefaultText = "";
            this.Input_Stock.FillColor = System.Drawing.Color.White;
            this.Input_Stock.HideSelection = true;
            this.Input_Stock.IconLeft = null;
            this.Input_Stock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Stock.IconPadding = 10;
            this.Input_Stock.IconRight = null;
            this.Input_Stock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Stock.Lines = new string[0];
            this.Input_Stock.Location = new System.Drawing.Point(28, 136);
            this.Input_Stock.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Stock.MaxLength = 32767;
            this.Input_Stock.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Stock.Modified = false;
            this.Input_Stock.Multiline = false;
            this.Input_Stock.Name = "Input_Stock";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Stock.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Stock.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Stock.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Stock.OnIdleState = stateProperties12;
            this.Input_Stock.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Stock.PasswordChar = '\0';
            this.Input_Stock.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Stock.PlaceholderText = "Stock Quantity";
            this.Input_Stock.ReadOnly = false;
            this.Input_Stock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Stock.SelectedText = "";
            this.Input_Stock.SelectionLength = 0;
            this.Input_Stock.SelectionStart = 0;
            this.Input_Stock.ShortcutsEnabled = true;
            this.Input_Stock.Size = new System.Drawing.Size(110, 34);
            this.Input_Stock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Stock.TabIndex = 3;
            this.Input_Stock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Stock.TextMarginBottom = 0;
            this.Input_Stock.TextMarginLeft = 3;
            this.Input_Stock.TextMarginTop = 0;
            this.Input_Stock.TextPlaceholder = "Stock Quantity";
            this.Input_Stock.UseSystemPasswordChar = false;
            this.Input_Stock.WordWrap = true;
            // 
            // Input_ProductCategory
            // 
            this.Input_ProductCategory.AcceptsReturn = false;
            this.Input_ProductCategory.AcceptsTab = false;
            this.Input_ProductCategory.AnimationSpeed = 200;
            this.Input_ProductCategory.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_ProductCategory.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_ProductCategory.BackColor = System.Drawing.Color.Transparent;
            this.Input_ProductCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_ProductCategory.BackgroundImage")));
            this.Input_ProductCategory.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_ProductCategory.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_ProductCategory.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_ProductCategory.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_ProductCategory.BorderRadius = 6;
            this.Input_ProductCategory.BorderThickness = 1;
            this.Input_ProductCategory.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_ProductCategory.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductCategory.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_ProductCategory.DefaultText = "";
            this.Input_ProductCategory.FillColor = System.Drawing.Color.White;
            this.Input_ProductCategory.HideSelection = true;
            this.Input_ProductCategory.IconLeft = null;
            this.Input_ProductCategory.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductCategory.IconPadding = 10;
            this.Input_ProductCategory.IconRight = null;
            this.Input_ProductCategory.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductCategory.Lines = new string[0];
            this.Input_ProductCategory.Location = new System.Drawing.Point(28, 94);
            this.Input_ProductCategory.Margin = new System.Windows.Forms.Padding(2);
            this.Input_ProductCategory.MaxLength = 32767;
            this.Input_ProductCategory.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_ProductCategory.Modified = false;
            this.Input_ProductCategory.Multiline = false;
            this.Input_ProductCategory.Name = "Input_ProductCategory";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductCategory.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_ProductCategory.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductCategory.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductCategory.OnIdleState = stateProperties16;
            this.Input_ProductCategory.Padding = new System.Windows.Forms.Padding(2);
            this.Input_ProductCategory.PasswordChar = '\0';
            this.Input_ProductCategory.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_ProductCategory.PlaceholderText = "Category";
            this.Input_ProductCategory.ReadOnly = false;
            this.Input_ProductCategory.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_ProductCategory.SelectedText = "";
            this.Input_ProductCategory.SelectionLength = 0;
            this.Input_ProductCategory.SelectionStart = 0;
            this.Input_ProductCategory.ShortcutsEnabled = true;
            this.Input_ProductCategory.Size = new System.Drawing.Size(229, 34);
            this.Input_ProductCategory.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_ProductCategory.TabIndex = 2;
            this.Input_ProductCategory.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_ProductCategory.TextMarginBottom = 0;
            this.Input_ProductCategory.TextMarginLeft = 3;
            this.Input_ProductCategory.TextMarginTop = 0;
            this.Input_ProductCategory.TextPlaceholder = "Category";
            this.Input_ProductCategory.UseSystemPasswordChar = false;
            this.Input_ProductCategory.WordWrap = true;
            // 
            // lbl_BioInfo
            // 
            this.lbl_BioInfo.AllowParentOverrides = false;
            this.lbl_BioInfo.AutoEllipsis = false;
            this.lbl_BioInfo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_BioInfo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_BioInfo.Font = new System.Drawing.Font("Ebrima", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_BioInfo.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.lbl_BioInfo.Location = new System.Drawing.Point(32, 17);
            this.lbl_BioInfo.Name = "lbl_BioInfo";
            this.lbl_BioInfo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_BioInfo.Size = new System.Drawing.Size(144, 20);
            this.lbl_BioInfo.TabIndex = 1;
            this.lbl_BioInfo.Text = "Product Information";
            this.lbl_BioInfo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_BioInfo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Input_ProductName
            // 
            this.Input_ProductName.AcceptsReturn = false;
            this.Input_ProductName.AcceptsTab = false;
            this.Input_ProductName.AnimationSpeed = 200;
            this.Input_ProductName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_ProductName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_ProductName.BackColor = System.Drawing.Color.Transparent;
            this.Input_ProductName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_ProductName.BackgroundImage")));
            this.Input_ProductName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_ProductName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_ProductName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_ProductName.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_ProductName.BorderRadius = 6;
            this.Input_ProductName.BorderThickness = 1;
            this.Input_ProductName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_ProductName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_ProductName.DefaultText = "";
            this.Input_ProductName.FillColor = System.Drawing.Color.White;
            this.Input_ProductName.HideSelection = true;
            this.Input_ProductName.IconLeft = null;
            this.Input_ProductName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductName.IconPadding = 10;
            this.Input_ProductName.IconRight = null;
            this.Input_ProductName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_ProductName.Lines = new string[0];
            this.Input_ProductName.Location = new System.Drawing.Point(28, 52);
            this.Input_ProductName.Margin = new System.Windows.Forms.Padding(2);
            this.Input_ProductName.MaxLength = 32767;
            this.Input_ProductName.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_ProductName.Modified = false;
            this.Input_ProductName.Multiline = false;
            this.Input_ProductName.Name = "Input_ProductName";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_ProductName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_ProductName.OnIdleState = stateProperties20;
            this.Input_ProductName.Padding = new System.Windows.Forms.Padding(2);
            this.Input_ProductName.PasswordChar = '\0';
            this.Input_ProductName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_ProductName.PlaceholderText = "Product Name";
            this.Input_ProductName.ReadOnly = false;
            this.Input_ProductName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_ProductName.SelectedText = "";
            this.Input_ProductName.SelectionLength = 0;
            this.Input_ProductName.SelectionStart = 0;
            this.Input_ProductName.ShortcutsEnabled = true;
            this.Input_ProductName.Size = new System.Drawing.Size(229, 34);
            this.Input_ProductName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_ProductName.TabIndex = 0;
            this.Input_ProductName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_ProductName.TextMarginBottom = 0;
            this.Input_ProductName.TextMarginLeft = 3;
            this.Input_ProductName.TextMarginTop = 0;
            this.Input_ProductName.TextPlaceholder = "Product Name";
            this.Input_ProductName.UseSystemPasswordChar = false;
            this.Input_ProductName.WordWrap = true;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 10;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.btn_AddProduct);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.Input_Details);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(3, 200);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 2;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(513, 262);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 16;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Ebrima", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.bunifuLabel1.Location = new System.Drawing.Point(28, 19);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(139, 20);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Product Description";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Input_Details
            // 
            this.Input_Details.AcceptsReturn = false;
            this.Input_Details.AcceptsTab = false;
            this.Input_Details.AnimationSpeed = 200;
            this.Input_Details.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Details.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Details.BackColor = System.Drawing.Color.Transparent;
            this.Input_Details.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Details.BackgroundImage")));
            this.Input_Details.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Details.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Details.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Details.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Details.BorderRadius = 6;
            this.Input_Details.BorderThickness = 1;
            this.Input_Details.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Details.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Details.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Details.DefaultText = "";
            this.Input_Details.FillColor = System.Drawing.Color.White;
            this.Input_Details.HideSelection = true;
            this.Input_Details.IconLeft = null;
            this.Input_Details.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Details.IconPadding = 10;
            this.Input_Details.IconRight = null;
            this.Input_Details.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Details.Lines = new string[0];
            this.Input_Details.Location = new System.Drawing.Point(28, 59);
            this.Input_Details.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Details.MaxLength = 32767;
            this.Input_Details.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Details.Modified = false;
            this.Input_Details.Multiline = true;
            this.Input_Details.Name = "Input_Details";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Details.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Details.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Details.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Details.OnIdleState = stateProperties4;
            this.Input_Details.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Details.PasswordChar = '\0';
            this.Input_Details.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Details.PlaceholderText = "Product Description... Write here";
            this.Input_Details.ReadOnly = false;
            this.Input_Details.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Details.SelectedText = "";
            this.Input_Details.SelectionLength = 0;
            this.Input_Details.SelectionStart = 0;
            this.Input_Details.ShortcutsEnabled = true;
            this.Input_Details.Size = new System.Drawing.Size(468, 150);
            this.Input_Details.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Details.TabIndex = 0;
            this.Input_Details.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Details.TextMarginBottom = 0;
            this.Input_Details.TextMarginLeft = 3;
            this.Input_Details.TextMarginTop = 0;
            this.Input_Details.TextPlaceholder = "Product Description... Write here";
            this.Input_Details.UseSystemPasswordChar = false;
            this.Input_Details.WordWrap = true;
            // 
            // btn_AddProduct
            // 
            this.btn_AddProduct.AllowAnimations = true;
            this.btn_AddProduct.AllowMouseEffects = true;
            this.btn_AddProduct.AllowToggling = false;
            this.btn_AddProduct.AnimationSpeed = 200;
            this.btn_AddProduct.AutoGenerateColors = false;
            this.btn_AddProduct.AutoRoundBorders = false;
            this.btn_AddProduct.AutoSizeLeftIcon = true;
            this.btn_AddProduct.AutoSizeRightIcon = true;
            this.btn_AddProduct.BackColor = System.Drawing.Color.Transparent;
            this.btn_AddProduct.BackColor1 = System.Drawing.Color.RoyalBlue;
            this.btn_AddProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_AddProduct.BackgroundImage")));
            this.btn_AddProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_AddProduct.ButtonText = "Add Product";
            this.btn_AddProduct.ButtonTextMarginLeft = 0;
            this.btn_AddProduct.ColorContrastOnClick = 45;
            this.btn_AddProduct.ColorContrastOnHover = 45;
            this.btn_AddProduct.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_AddProduct.CustomizableEdges = borderEdges1;
            this.btn_AddProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_AddProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_AddProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_AddProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_AddProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_AddProduct.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_AddProduct.ForeColor = System.Drawing.Color.White;
            this.btn_AddProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_AddProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_AddProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_AddProduct.IconMarginLeft = 11;
            this.btn_AddProduct.IconPadding = 10;
            this.btn_AddProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_AddProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_AddProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_AddProduct.IconSize = 25;
            this.btn_AddProduct.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_AddProduct.IdleBorderRadius = 15;
            this.btn_AddProduct.IdleBorderThickness = 2;
            this.btn_AddProduct.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btn_AddProduct.IdleIconLeftImage = null;
            this.btn_AddProduct.IdleIconRightImage = null;
            this.btn_AddProduct.IndicateFocus = false;
            this.btn_AddProduct.Location = new System.Drawing.Point(398, 217);
            this.btn_AddProduct.Name = "btn_AddProduct";
            this.btn_AddProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_AddProduct.OnDisabledState.BorderRadius = 15;
            this.btn_AddProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_AddProduct.OnDisabledState.BorderThickness = 2;
            this.btn_AddProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_AddProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_AddProduct.OnDisabledState.IconLeftImage = null;
            this.btn_AddProduct.OnDisabledState.IconRightImage = null;
            this.btn_AddProduct.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_AddProduct.onHoverState.BorderRadius = 15;
            this.btn_AddProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_AddProduct.onHoverState.BorderThickness = 2;
            this.btn_AddProduct.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_AddProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_AddProduct.onHoverState.IconLeftImage = null;
            this.btn_AddProduct.onHoverState.IconRightImage = null;
            this.btn_AddProduct.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_AddProduct.OnIdleState.BorderRadius = 15;
            this.btn_AddProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_AddProduct.OnIdleState.BorderThickness = 2;
            this.btn_AddProduct.OnIdleState.FillColor = System.Drawing.Color.RoyalBlue;
            this.btn_AddProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_AddProduct.OnIdleState.IconLeftImage = null;
            this.btn_AddProduct.OnIdleState.IconRightImage = null;
            this.btn_AddProduct.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_AddProduct.OnPressedState.BorderRadius = 15;
            this.btn_AddProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_AddProduct.OnPressedState.BorderThickness = 2;
            this.btn_AddProduct.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_AddProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_AddProduct.OnPressedState.IconLeftImage = null;
            this.btn_AddProduct.OnPressedState.IconRightImage = null;
            this.btn_AddProduct.Size = new System.Drawing.Size(98, 31);
            this.btn_AddProduct.TabIndex = 28;
            this.btn_AddProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_AddProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_AddProduct.TextMarginLeft = 0;
            this.btn_AddProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_AddProduct.UseDefaultRadiusAndThickness = true;
            this.btn_AddProduct.Click += new System.EventHandler(this.btn_AddProduct_Click);
            // 
            // btn_ImgUpload
            // 
            this.btn_ImgUpload.AllowAnimations = true;
            this.btn_ImgUpload.AllowMouseEffects = true;
            this.btn_ImgUpload.AllowToggling = false;
            this.btn_ImgUpload.AnimationSpeed = 200;
            this.btn_ImgUpload.AutoGenerateColors = false;
            this.btn_ImgUpload.AutoRoundBorders = false;
            this.btn_ImgUpload.AutoSizeLeftIcon = true;
            this.btn_ImgUpload.AutoSizeRightIcon = true;
            this.btn_ImgUpload.BackColor = System.Drawing.Color.Transparent;
            this.btn_ImgUpload.BackColor1 = System.Drawing.Color.LightSlateGray;
            this.btn_ImgUpload.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_ImgUpload.BackgroundImage")));
            this.btn_ImgUpload.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ImgUpload.ButtonText = "Upload Image";
            this.btn_ImgUpload.ButtonTextMarginLeft = 0;
            this.btn_ImgUpload.ColorContrastOnClick = 45;
            this.btn_ImgUpload.ColorContrastOnHover = 45;
            this.btn_ImgUpload.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_ImgUpload.CustomizableEdges = borderEdges2;
            this.btn_ImgUpload.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_ImgUpload.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ImgUpload.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ImgUpload.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ImgUpload.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_ImgUpload.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_ImgUpload.ForeColor = System.Drawing.Color.White;
            this.btn_ImgUpload.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_ImgUpload.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ImgUpload.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_ImgUpload.IconMarginLeft = 11;
            this.btn_ImgUpload.IconPadding = 10;
            this.btn_ImgUpload.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_ImgUpload.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_ImgUpload.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_ImgUpload.IconSize = 25;
            this.btn_ImgUpload.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_ImgUpload.IdleBorderRadius = 15;
            this.btn_ImgUpload.IdleBorderThickness = 2;
            this.btn_ImgUpload.IdleFillColor = System.Drawing.Color.LightSlateGray;
            this.btn_ImgUpload.IdleIconLeftImage = null;
            this.btn_ImgUpload.IdleIconRightImage = null;
            this.btn_ImgUpload.IndicateFocus = false;
            this.btn_ImgUpload.Location = new System.Drawing.Point(329, 139);
            this.btn_ImgUpload.Name = "btn_ImgUpload";
            this.btn_ImgUpload.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_ImgUpload.OnDisabledState.BorderRadius = 15;
            this.btn_ImgUpload.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ImgUpload.OnDisabledState.BorderThickness = 2;
            this.btn_ImgUpload.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ImgUpload.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ImgUpload.OnDisabledState.IconLeftImage = null;
            this.btn_ImgUpload.OnDisabledState.IconRightImage = null;
            this.btn_ImgUpload.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_ImgUpload.onHoverState.BorderRadius = 15;
            this.btn_ImgUpload.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ImgUpload.onHoverState.BorderThickness = 2;
            this.btn_ImgUpload.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_ImgUpload.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_ImgUpload.onHoverState.IconLeftImage = null;
            this.btn_ImgUpload.onHoverState.IconRightImage = null;
            this.btn_ImgUpload.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_ImgUpload.OnIdleState.BorderRadius = 15;
            this.btn_ImgUpload.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ImgUpload.OnIdleState.BorderThickness = 2;
            this.btn_ImgUpload.OnIdleState.FillColor = System.Drawing.Color.LightSlateGray;
            this.btn_ImgUpload.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_ImgUpload.OnIdleState.IconLeftImage = null;
            this.btn_ImgUpload.OnIdleState.IconRightImage = null;
            this.btn_ImgUpload.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_ImgUpload.OnPressedState.BorderRadius = 15;
            this.btn_ImgUpload.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ImgUpload.OnPressedState.BorderThickness = 2;
            this.btn_ImgUpload.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_ImgUpload.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_ImgUpload.OnPressedState.IconLeftImage = null;
            this.btn_ImgUpload.OnPressedState.IconRightImage = null;
            this.btn_ImgUpload.Size = new System.Drawing.Size(112, 31);
            this.btn_ImgUpload.TabIndex = 29;
            this.btn_ImgUpload.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_ImgUpload.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_ImgUpload.TextMarginLeft = 0;
            this.btn_ImgUpload.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_ImgUpload.UseDefaultRadiusAndThickness = true;
            this.btn_ImgUpload.Click += new System.EventHandler(this.btn_ImgUpload_Click);
            // 
            // Input_Price
            // 
            this.Input_Price.AcceptsReturn = false;
            this.Input_Price.AcceptsTab = false;
            this.Input_Price.AnimationSpeed = 200;
            this.Input_Price.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Price.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Price.BackColor = System.Drawing.Color.Transparent;
            this.Input_Price.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Price.BackgroundImage")));
            this.Input_Price.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Price.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Price.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Price.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Price.BorderRadius = 6;
            this.Input_Price.BorderThickness = 1;
            this.Input_Price.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Price.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Price.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Price.DefaultText = "";
            this.Input_Price.FillColor = System.Drawing.Color.White;
            this.Input_Price.HideSelection = true;
            this.Input_Price.IconLeft = null;
            this.Input_Price.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Price.IconPadding = 10;
            this.Input_Price.IconRight = null;
            this.Input_Price.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Price.Lines = new string[0];
            this.Input_Price.Location = new System.Drawing.Point(146, 136);
            this.Input_Price.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Price.MaxLength = 32767;
            this.Input_Price.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Price.Modified = false;
            this.Input_Price.Multiline = false;
            this.Input_Price.Name = "Input_Price";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Price.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Price.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Price.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Price.OnIdleState = stateProperties8;
            this.Input_Price.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Price.PasswordChar = '\0';
            this.Input_Price.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Price.PlaceholderText = "Price";
            this.Input_Price.ReadOnly = false;
            this.Input_Price.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Price.SelectedText = "";
            this.Input_Price.SelectionLength = 0;
            this.Input_Price.SelectionStart = 0;
            this.Input_Price.ShortcutsEnabled = true;
            this.Input_Price.Size = new System.Drawing.Size(110, 34);
            this.Input_Price.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Price.TabIndex = 30;
            this.Input_Price.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Price.TextMarginBottom = 0;
            this.Input_Price.TextMarginLeft = 3;
            this.Input_Price.TextMarginTop = 0;
            this.Input_Price.TextPlaceholder = "Price";
            this.Input_Price.UseSystemPasswordChar = false;
            this.Input_Price.WordWrap = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(303, 17);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(165, 116);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 31;
            this.pictureBox1.TabStop = false;
            // 
            // AdminAddProduct
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuShadowPanel3);
            this.Name = "AdminAddProduct";
            this.Size = new System.Drawing.Size(525, 471);
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Details;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Stock;
        private Bunifu.UI.WinForms.BunifuTextBox Input_ProductCategory;
        private Bunifu.UI.WinForms.BunifuLabel lbl_BioInfo;
        private Bunifu.UI.WinForms.BunifuTextBox Input_ProductName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_AddProduct;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Price;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_ImgUpload;
    }
}
