namespace V_Mart
{
    partial class SignUpCustomer
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SignUpCustomer));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties109 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties110 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties111 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties112 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties113 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties114 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties115 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties116 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties117 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties118 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties119 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties120 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties121 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties122 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties123 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties124 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties125 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties126 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties127 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties128 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties129 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties130 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties131 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties132 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties133 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties134 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties135 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties136 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties137 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties138 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties139 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties140 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties141 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties142 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties143 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties144 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Input_FirstName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_BioInfo = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.Input_PhoneNum = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Input_Age = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Input_LastName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btn_SignUp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Cancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn_Undertaking = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.Input_Country = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Input_City = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Input_Address = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Input_Password = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Input_Email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_otherinfo = new Bunifu.UI.WinForms.BunifuLabel();
            this.guna2CircleButton3 = new Guna.UI2.WinForms.Guna2CircleButton();
            this.guna2CircleButton2 = new Guna.UI2.WinForms.Guna2CircleButton();
            this.btn_Close = new Guna.UI2.WinForms.Guna2CircleButton();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.bunifuShadowPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            this.bunifuShadowPanel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // Input_FirstName
            // 
            this.Input_FirstName.AcceptsReturn = false;
            this.Input_FirstName.AcceptsTab = false;
            this.Input_FirstName.AnimationSpeed = 200;
            this.Input_FirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_FirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_FirstName.BackColor = System.Drawing.Color.Transparent;
            this.Input_FirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_FirstName.BackgroundImage")));
            this.Input_FirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_FirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_FirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_FirstName.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_FirstName.BorderRadius = 6;
            this.Input_FirstName.BorderThickness = 1;
            this.Input_FirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_FirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_FirstName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_FirstName.DefaultText = "";
            this.Input_FirstName.FillColor = System.Drawing.Color.White;
            this.Input_FirstName.HideSelection = true;
            this.Input_FirstName.IconLeft = null;
            this.Input_FirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_FirstName.IconPadding = 10;
            this.Input_FirstName.IconRight = null;
            this.Input_FirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_FirstName.Lines = new string[0];
            this.Input_FirstName.Location = new System.Drawing.Point(28, 59);
            this.Input_FirstName.Margin = new System.Windows.Forms.Padding(2);
            this.Input_FirstName.MaxLength = 32767;
            this.Input_FirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_FirstName.Modified = false;
            this.Input_FirstName.Multiline = false;
            this.Input_FirstName.Name = "Input_FirstName";
            stateProperties109.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties109.FillColor = System.Drawing.Color.Empty;
            stateProperties109.ForeColor = System.Drawing.Color.Empty;
            stateProperties109.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_FirstName.OnActiveState = stateProperties109;
            stateProperties110.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties110.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties110.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties110.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_FirstName.OnDisabledState = stateProperties110;
            stateProperties111.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties111.FillColor = System.Drawing.Color.Empty;
            stateProperties111.ForeColor = System.Drawing.Color.Empty;
            stateProperties111.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_FirstName.OnHoverState = stateProperties111;
            stateProperties112.BorderColor = System.Drawing.Color.Silver;
            stateProperties112.FillColor = System.Drawing.Color.White;
            stateProperties112.ForeColor = System.Drawing.Color.Empty;
            stateProperties112.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_FirstName.OnIdleState = stateProperties112;
            this.Input_FirstName.Padding = new System.Windows.Forms.Padding(2);
            this.Input_FirstName.PasswordChar = '\0';
            this.Input_FirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_FirstName.PlaceholderText = "First Name";
            this.Input_FirstName.ReadOnly = false;
            this.Input_FirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_FirstName.SelectedText = "";
            this.Input_FirstName.SelectionLength = 0;
            this.Input_FirstName.SelectionStart = 0;
            this.Input_FirstName.ShortcutsEnabled = true;
            this.Input_FirstName.Size = new System.Drawing.Size(229, 34);
            this.Input_FirstName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_FirstName.TabIndex = 0;
            this.Input_FirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_FirstName.TextMarginBottom = 0;
            this.Input_FirstName.TextMarginLeft = 3;
            this.Input_FirstName.TextMarginTop = 0;
            this.Input_FirstName.TextPlaceholder = "First Name";
            this.Input_FirstName.UseSystemPasswordChar = false;
            this.Input_FirstName.WordWrap = true;
            // 
            // lbl_BioInfo
            // 
            this.lbl_BioInfo.AllowParentOverrides = false;
            this.lbl_BioInfo.AutoEllipsis = false;
            this.lbl_BioInfo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_BioInfo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_BioInfo.Font = new System.Drawing.Font("Ebrima", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_BioInfo.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.lbl_BioInfo.Location = new System.Drawing.Point(28, 21);
            this.lbl_BioInfo.Name = "lbl_BioInfo";
            this.lbl_BioInfo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_BioInfo.Size = new System.Drawing.Size(157, 20);
            this.lbl_BioInfo.TabIndex = 1;
            this.lbl_BioInfo.Text = "Biological Information";
            this.lbl_BioInfo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_BioInfo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 153;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(24, 59);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(306, 306);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 2;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 10;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(12, 12);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 2;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(360, 542);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 9;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Ebrima", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.bunifuLabel5.Location = new System.Drawing.Point(286, 512);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(29, 15);
            this.bunifuLabel5.TabIndex = 13;
            this.bunifuLabel5.Text = "FAQS";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Ebrima", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.bunifuLabel4.Location = new System.Drawing.Point(156, 512);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(57, 15);
            this.bunifuLabel4.TabIndex = 12;
            this.bunifuLabel4.Text = "Contact Us";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Ebrima", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.bunifuLabel3.Location = new System.Drawing.Point(24, 512);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(81, 15);
            this.bunifuLabel3.TabIndex = 11;
            this.bunifuLabel3.Text = "Privacy Policies";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Ebrima", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.bunifuLabel2.Location = new System.Drawing.Point(34, 358);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(296, 45);
            this.bunifuLabel2.TabIndex = 10;
            this.bunifuLabel2.Text = "Join Us and Explore";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.BorderRadius = 10;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.Input_PhoneNum);
            this.bunifuShadowPanel2.Controls.Add(this.Input_Age);
            this.bunifuShadowPanel2.Controls.Add(this.Input_LastName);
            this.bunifuShadowPanel2.Controls.Add(this.lbl_BioInfo);
            this.bunifuShadowPanel2.Controls.Add(this.Input_FirstName);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(378, 34);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 2;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(670, 191);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 14;
            // 
            // Input_PhoneNum
            // 
            this.Input_PhoneNum.AcceptsReturn = false;
            this.Input_PhoneNum.AcceptsTab = false;
            this.Input_PhoneNum.AnimationSpeed = 200;
            this.Input_PhoneNum.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_PhoneNum.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_PhoneNum.BackColor = System.Drawing.Color.Transparent;
            this.Input_PhoneNum.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_PhoneNum.BackgroundImage")));
            this.Input_PhoneNum.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_PhoneNum.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_PhoneNum.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_PhoneNum.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_PhoneNum.BorderRadius = 6;
            this.Input_PhoneNum.BorderThickness = 1;
            this.Input_PhoneNum.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_PhoneNum.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_PhoneNum.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_PhoneNum.DefaultText = "";
            this.Input_PhoneNum.FillColor = System.Drawing.Color.White;
            this.Input_PhoneNum.HideSelection = true;
            this.Input_PhoneNum.IconLeft = null;
            this.Input_PhoneNum.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_PhoneNum.IconPadding = 10;
            this.Input_PhoneNum.IconRight = null;
            this.Input_PhoneNum.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_PhoneNum.Lines = new string[0];
            this.Input_PhoneNum.Location = new System.Drawing.Point(28, 123);
            this.Input_PhoneNum.Margin = new System.Windows.Forms.Padding(2);
            this.Input_PhoneNum.MaxLength = 32767;
            this.Input_PhoneNum.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_PhoneNum.Modified = false;
            this.Input_PhoneNum.Multiline = false;
            this.Input_PhoneNum.Name = "Input_PhoneNum";
            stateProperties113.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties113.FillColor = System.Drawing.Color.Empty;
            stateProperties113.ForeColor = System.Drawing.Color.Empty;
            stateProperties113.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_PhoneNum.OnActiveState = stateProperties113;
            stateProperties114.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties114.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties114.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties114.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_PhoneNum.OnDisabledState = stateProperties114;
            stateProperties115.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties115.FillColor = System.Drawing.Color.Empty;
            stateProperties115.ForeColor = System.Drawing.Color.Empty;
            stateProperties115.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_PhoneNum.OnHoverState = stateProperties115;
            stateProperties116.BorderColor = System.Drawing.Color.Silver;
            stateProperties116.FillColor = System.Drawing.Color.White;
            stateProperties116.ForeColor = System.Drawing.Color.Empty;
            stateProperties116.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_PhoneNum.OnIdleState = stateProperties116;
            this.Input_PhoneNum.Padding = new System.Windows.Forms.Padding(2);
            this.Input_PhoneNum.PasswordChar = '\0';
            this.Input_PhoneNum.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_PhoneNum.PlaceholderText = "Phone Number";
            this.Input_PhoneNum.ReadOnly = false;
            this.Input_PhoneNum.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_PhoneNum.SelectedText = "";
            this.Input_PhoneNum.SelectionLength = 0;
            this.Input_PhoneNum.SelectionStart = 0;
            this.Input_PhoneNum.ShortcutsEnabled = true;
            this.Input_PhoneNum.Size = new System.Drawing.Size(229, 34);
            this.Input_PhoneNum.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_PhoneNum.TabIndex = 4;
            this.Input_PhoneNum.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_PhoneNum.TextMarginBottom = 0;
            this.Input_PhoneNum.TextMarginLeft = 3;
            this.Input_PhoneNum.TextMarginTop = 0;
            this.Input_PhoneNum.TextPlaceholder = "Phone Number";
            this.Input_PhoneNum.UseSystemPasswordChar = false;
            this.Input_PhoneNum.WordWrap = true;
            // 
            // Input_Age
            // 
            this.Input_Age.AcceptsReturn = false;
            this.Input_Age.AcceptsTab = false;
            this.Input_Age.AnimationSpeed = 200;
            this.Input_Age.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Age.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Age.BackColor = System.Drawing.Color.Transparent;
            this.Input_Age.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Age.BackgroundImage")));
            this.Input_Age.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Age.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Age.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Age.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Age.BorderRadius = 6;
            this.Input_Age.BorderThickness = 1;
            this.Input_Age.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Age.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Age.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Age.DefaultText = "";
            this.Input_Age.FillColor = System.Drawing.Color.White;
            this.Input_Age.HideSelection = true;
            this.Input_Age.IconLeft = null;
            this.Input_Age.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Age.IconPadding = 10;
            this.Input_Age.IconRight = null;
            this.Input_Age.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Age.Lines = new string[0];
            this.Input_Age.Location = new System.Drawing.Point(281, 123);
            this.Input_Age.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Age.MaxLength = 32767;
            this.Input_Age.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Age.Modified = false;
            this.Input_Age.Multiline = false;
            this.Input_Age.Name = "Input_Age";
            stateProperties117.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties117.FillColor = System.Drawing.Color.Empty;
            stateProperties117.ForeColor = System.Drawing.Color.Empty;
            stateProperties117.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Age.OnActiveState = stateProperties117;
            stateProperties118.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties118.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties118.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties118.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Age.OnDisabledState = stateProperties118;
            stateProperties119.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties119.FillColor = System.Drawing.Color.Empty;
            stateProperties119.ForeColor = System.Drawing.Color.Empty;
            stateProperties119.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Age.OnHoverState = stateProperties119;
            stateProperties120.BorderColor = System.Drawing.Color.Silver;
            stateProperties120.FillColor = System.Drawing.Color.White;
            stateProperties120.ForeColor = System.Drawing.Color.Empty;
            stateProperties120.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Age.OnIdleState = stateProperties120;
            this.Input_Age.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Age.PasswordChar = '\0';
            this.Input_Age.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Age.PlaceholderText = "Age";
            this.Input_Age.ReadOnly = false;
            this.Input_Age.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Age.SelectedText = "";
            this.Input_Age.SelectionLength = 0;
            this.Input_Age.SelectionStart = 0;
            this.Input_Age.ShortcutsEnabled = true;
            this.Input_Age.Size = new System.Drawing.Size(77, 34);
            this.Input_Age.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Age.TabIndex = 3;
            this.Input_Age.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Age.TextMarginBottom = 0;
            this.Input_Age.TextMarginLeft = 3;
            this.Input_Age.TextMarginTop = 0;
            this.Input_Age.TextPlaceholder = "Age";
            this.Input_Age.UseSystemPasswordChar = false;
            this.Input_Age.WordWrap = true;
            // 
            // Input_LastName
            // 
            this.Input_LastName.AcceptsReturn = false;
            this.Input_LastName.AcceptsTab = false;
            this.Input_LastName.AnimationSpeed = 200;
            this.Input_LastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_LastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_LastName.BackColor = System.Drawing.Color.Transparent;
            this.Input_LastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_LastName.BackgroundImage")));
            this.Input_LastName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_LastName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_LastName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_LastName.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_LastName.BorderRadius = 6;
            this.Input_LastName.BorderThickness = 1;
            this.Input_LastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_LastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_LastName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_LastName.DefaultText = "";
            this.Input_LastName.FillColor = System.Drawing.Color.White;
            this.Input_LastName.HideSelection = true;
            this.Input_LastName.IconLeft = null;
            this.Input_LastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_LastName.IconPadding = 10;
            this.Input_LastName.IconRight = null;
            this.Input_LastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_LastName.Lines = new string[0];
            this.Input_LastName.Location = new System.Drawing.Point(281, 59);
            this.Input_LastName.Margin = new System.Windows.Forms.Padding(2);
            this.Input_LastName.MaxLength = 32767;
            this.Input_LastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_LastName.Modified = false;
            this.Input_LastName.Multiline = false;
            this.Input_LastName.Name = "Input_LastName";
            stateProperties121.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties121.FillColor = System.Drawing.Color.Empty;
            stateProperties121.ForeColor = System.Drawing.Color.Empty;
            stateProperties121.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_LastName.OnActiveState = stateProperties121;
            stateProperties122.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties122.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties122.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties122.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_LastName.OnDisabledState = stateProperties122;
            stateProperties123.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties123.FillColor = System.Drawing.Color.Empty;
            stateProperties123.ForeColor = System.Drawing.Color.Empty;
            stateProperties123.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_LastName.OnHoverState = stateProperties123;
            stateProperties124.BorderColor = System.Drawing.Color.Silver;
            stateProperties124.FillColor = System.Drawing.Color.White;
            stateProperties124.ForeColor = System.Drawing.Color.Empty;
            stateProperties124.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_LastName.OnIdleState = stateProperties124;
            this.Input_LastName.Padding = new System.Windows.Forms.Padding(2);
            this.Input_LastName.PasswordChar = '\0';
            this.Input_LastName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_LastName.PlaceholderText = "Last Name";
            this.Input_LastName.ReadOnly = false;
            this.Input_LastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_LastName.SelectedText = "";
            this.Input_LastName.SelectionLength = 0;
            this.Input_LastName.SelectionStart = 0;
            this.Input_LastName.ShortcutsEnabled = true;
            this.Input_LastName.Size = new System.Drawing.Size(229, 34);
            this.Input_LastName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_LastName.TabIndex = 2;
            this.Input_LastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_LastName.TextMarginBottom = 0;
            this.Input_LastName.TextMarginLeft = 3;
            this.Input_LastName.TextMarginTop = 0;
            this.Input_LastName.TextPlaceholder = "Last Name";
            this.Input_LastName.UseSystemPasswordChar = false;
            this.Input_LastName.WordWrap = true;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.BorderRadius = 10;
            this.bunifuShadowPanel3.BorderThickness = 1;
            this.bunifuShadowPanel3.Controls.Add(this.btn_SignUp);
            this.bunifuShadowPanel3.Controls.Add(this.btn_Cancel);
            this.bunifuShadowPanel3.Controls.Add(this.bunifuLabel8);
            this.bunifuShadowPanel3.Controls.Add(this.btn_Undertaking);
            this.bunifuShadowPanel3.Controls.Add(this.Input_Country);
            this.bunifuShadowPanel3.Controls.Add(this.Input_City);
            this.bunifuShadowPanel3.Controls.Add(this.Input_Address);
            this.bunifuShadowPanel3.Controls.Add(this.Input_Password);
            this.bunifuShadowPanel3.Controls.Add(this.Input_Email);
            this.bunifuShadowPanel3.Controls.Add(this.lbl_otherinfo);
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(378, 231);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 2;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(670, 323);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 15;
            // 
            // btn_SignUp
            // 
            this.btn_SignUp.AllowAnimations = true;
            this.btn_SignUp.AllowMouseEffects = true;
            this.btn_SignUp.AllowToggling = false;
            this.btn_SignUp.AnimationSpeed = 200;
            this.btn_SignUp.AutoGenerateColors = false;
            this.btn_SignUp.AutoRoundBorders = false;
            this.btn_SignUp.AutoSizeLeftIcon = true;
            this.btn_SignUp.AutoSizeRightIcon = true;
            this.btn_SignUp.BackColor = System.Drawing.Color.Transparent;
            this.btn_SignUp.BackColor1 = System.Drawing.Color.Navy;
            this.btn_SignUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SignUp.BackgroundImage")));
            this.btn_SignUp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignUp.ButtonText = "Sign Up";
            this.btn_SignUp.ButtonTextMarginLeft = 0;
            this.btn_SignUp.ColorContrastOnClick = 45;
            this.btn_SignUp.ColorContrastOnHover = 45;
            this.btn_SignUp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_SignUp.CustomizableEdges = borderEdges7;
            this.btn_SignUp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SignUp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_SignUp.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignUp.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignUp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_SignUp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_SignUp.ForeColor = System.Drawing.Color.White;
            this.btn_SignUp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_SignUp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SignUp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_SignUp.IconMarginLeft = 11;
            this.btn_SignUp.IconPadding = 10;
            this.btn_SignUp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_SignUp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_SignUp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_SignUp.IconSize = 25;
            this.btn_SignUp.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_SignUp.IdleBorderRadius = 15;
            this.btn_SignUp.IdleBorderThickness = 2;
            this.btn_SignUp.IdleFillColor = System.Drawing.Color.Navy;
            this.btn_SignUp.IdleIconLeftImage = null;
            this.btn_SignUp.IdleIconRightImage = null;
            this.btn_SignUp.IndicateFocus = false;
            this.btn_SignUp.Location = new System.Drawing.Point(525, 265);
            this.btn_SignUp.Name = "btn_SignUp";
            this.btn_SignUp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_SignUp.OnDisabledState.BorderRadius = 15;
            this.btn_SignUp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignUp.OnDisabledState.BorderThickness = 2;
            this.btn_SignUp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignUp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignUp.OnDisabledState.IconLeftImage = null;
            this.btn_SignUp.OnDisabledState.IconRightImage = null;
            this.btn_SignUp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_SignUp.onHoverState.BorderRadius = 15;
            this.btn_SignUp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignUp.onHoverState.BorderThickness = 2;
            this.btn_SignUp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_SignUp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_SignUp.onHoverState.IconLeftImage = null;
            this.btn_SignUp.onHoverState.IconRightImage = null;
            this.btn_SignUp.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_SignUp.OnIdleState.BorderRadius = 15;
            this.btn_SignUp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignUp.OnIdleState.BorderThickness = 2;
            this.btn_SignUp.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.btn_SignUp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_SignUp.OnIdleState.IconLeftImage = null;
            this.btn_SignUp.OnIdleState.IconRightImage = null;
            this.btn_SignUp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_SignUp.OnPressedState.BorderRadius = 15;
            this.btn_SignUp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignUp.OnPressedState.BorderThickness = 2;
            this.btn_SignUp.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_SignUp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_SignUp.OnPressedState.IconLeftImage = null;
            this.btn_SignUp.OnPressedState.IconRightImage = null;
            this.btn_SignUp.Size = new System.Drawing.Size(123, 39);
            this.btn_SignUp.TabIndex = 17;
            this.btn_SignUp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_SignUp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_SignUp.TextMarginLeft = 0;
            this.btn_SignUp.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_SignUp.UseDefaultRadiusAndThickness = true;
            this.btn_SignUp.Click += new System.EventHandler(this.btn_SignUp_Click);
            // 
            // btn_Cancel
            // 
            this.btn_Cancel.AllowAnimations = true;
            this.btn_Cancel.AllowMouseEffects = true;
            this.btn_Cancel.AllowToggling = false;
            this.btn_Cancel.AnimationSpeed = 200;
            this.btn_Cancel.AutoGenerateColors = false;
            this.btn_Cancel.AutoRoundBorders = false;
            this.btn_Cancel.AutoSizeLeftIcon = true;
            this.btn_Cancel.AutoSizeRightIcon = true;
            this.btn_Cancel.BackColor = System.Drawing.Color.Transparent;
            this.btn_Cancel.BackColor1 = System.Drawing.Color.LightGray;
            this.btn_Cancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Cancel.BackgroundImage")));
            this.btn_Cancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Cancel.ButtonText = "Cancel";
            this.btn_Cancel.ButtonTextMarginLeft = 0;
            this.btn_Cancel.ColorContrastOnClick = 45;
            this.btn_Cancel.ColorContrastOnHover = 45;
            this.btn_Cancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_Cancel.CustomizableEdges = borderEdges8;
            this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Cancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Cancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Cancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Cancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Cancel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_Cancel.ForeColor = System.Drawing.Color.White;
            this.btn_Cancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_Cancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Cancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_Cancel.IconMarginLeft = 11;
            this.btn_Cancel.IconPadding = 10;
            this.btn_Cancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_Cancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_Cancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_Cancel.IconSize = 25;
            this.btn_Cancel.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_Cancel.IdleBorderRadius = 15;
            this.btn_Cancel.IdleBorderThickness = 2;
            this.btn_Cancel.IdleFillColor = System.Drawing.Color.LightGray;
            this.btn_Cancel.IdleIconLeftImage = null;
            this.btn_Cancel.IdleIconRightImage = null;
            this.btn_Cancel.IndicateFocus = false;
            this.btn_Cancel.Location = new System.Drawing.Point(396, 265);
            this.btn_Cancel.Name = "btn_Cancel";
            this.btn_Cancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_Cancel.OnDisabledState.BorderRadius = 15;
            this.btn_Cancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Cancel.OnDisabledState.BorderThickness = 2;
            this.btn_Cancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Cancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Cancel.OnDisabledState.IconLeftImage = null;
            this.btn_Cancel.OnDisabledState.IconRightImage = null;
            this.btn_Cancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Cancel.onHoverState.BorderRadius = 15;
            this.btn_Cancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Cancel.onHoverState.BorderThickness = 2;
            this.btn_Cancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_Cancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_Cancel.onHoverState.IconLeftImage = null;
            this.btn_Cancel.onHoverState.IconRightImage = null;
            this.btn_Cancel.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_Cancel.OnIdleState.BorderRadius = 15;
            this.btn_Cancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Cancel.OnIdleState.BorderThickness = 2;
            this.btn_Cancel.OnIdleState.FillColor = System.Drawing.Color.LightGray;
            this.btn_Cancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_Cancel.OnIdleState.IconLeftImage = null;
            this.btn_Cancel.OnIdleState.IconRightImage = null;
            this.btn_Cancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Cancel.OnPressedState.BorderRadius = 15;
            this.btn_Cancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Cancel.OnPressedState.BorderThickness = 2;
            this.btn_Cancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Cancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_Cancel.OnPressedState.IconLeftImage = null;
            this.btn_Cancel.OnPressedState.IconRightImage = null;
            this.btn_Cancel.Size = new System.Drawing.Size(123, 39);
            this.btn_Cancel.TabIndex = 16;
            this.btn_Cancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Cancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_Cancel.TextMarginLeft = 0;
            this.btn_Cancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_Cancel.UseDefaultRadiusAndThickness = true;
            this.btn_Cancel.Click += new System.EventHandler(this.btn_Cancel_Click);
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Ebrima", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.bunifuLabel8.Location = new System.Drawing.Point(63, 233);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(268, 15);
            this.bunifuLabel8.TabIndex = 14;
            this.bunifuLabel8.Text = "I have read privacy policies and want to join V Mart";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btn_Undertaking
            // 
            this.btn_Undertaking.AllowBindingControlLocation = false;
            this.btn_Undertaking.BackColor = System.Drawing.Color.Transparent;
            this.btn_Undertaking.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.btn_Undertaking.BorderThickness = 1;
            this.btn_Undertaking.Checked = true;
            this.btn_Undertaking.Location = new System.Drawing.Point(34, 230);
            this.btn_Undertaking.Name = "btn_Undertaking";
            this.btn_Undertaking.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.btn_Undertaking.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Undertaking.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.btn_Undertaking.RadioColor = System.Drawing.Color.DodgerBlue;
            this.btn_Undertaking.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_Undertaking.Size = new System.Drawing.Size(21, 21);
            this.btn_Undertaking.TabIndex = 12;
            this.btn_Undertaking.Text = null;
            // 
            // Input_Country
            // 
            this.Input_Country.AcceptsReturn = false;
            this.Input_Country.AcceptsTab = false;
            this.Input_Country.AnimationSpeed = 200;
            this.Input_Country.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Country.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Country.BackColor = System.Drawing.Color.White;
            this.Input_Country.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Country.BackgroundImage")));
            this.Input_Country.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Country.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Country.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Country.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Country.BorderRadius = 6;
            this.Input_Country.BorderThickness = 1;
            this.Input_Country.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Country.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Country.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Country.DefaultText = "";
            this.Input_Country.FillColor = System.Drawing.Color.White;
            this.Input_Country.HideSelection = true;
            this.Input_Country.IconLeft = null;
            this.Input_Country.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Country.IconPadding = 10;
            this.Input_Country.IconRight = null;
            this.Input_Country.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Country.Lines = new string[0];
            this.Input_Country.Location = new System.Drawing.Point(381, 178);
            this.Input_Country.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Country.MaxLength = 32767;
            this.Input_Country.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Country.Modified = false;
            this.Input_Country.Multiline = false;
            this.Input_Country.Name = "Input_Country";
            stateProperties125.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties125.FillColor = System.Drawing.Color.Empty;
            stateProperties125.ForeColor = System.Drawing.Color.Empty;
            stateProperties125.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Country.OnActiveState = stateProperties125;
            stateProperties126.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties126.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties126.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties126.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Country.OnDisabledState = stateProperties126;
            stateProperties127.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties127.FillColor = System.Drawing.Color.Empty;
            stateProperties127.ForeColor = System.Drawing.Color.Empty;
            stateProperties127.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Country.OnHoverState = stateProperties127;
            stateProperties128.BorderColor = System.Drawing.Color.Silver;
            stateProperties128.FillColor = System.Drawing.Color.White;
            stateProperties128.ForeColor = System.Drawing.Color.Empty;
            stateProperties128.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Country.OnIdleState = stateProperties128;
            this.Input_Country.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Country.PasswordChar = '\0';
            this.Input_Country.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Country.PlaceholderText = "Country";
            this.Input_Country.ReadOnly = false;
            this.Input_Country.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Country.SelectedText = "";
            this.Input_Country.SelectionLength = 0;
            this.Input_Country.SelectionStart = 0;
            this.Input_Country.ShortcutsEnabled = true;
            this.Input_Country.Size = new System.Drawing.Size(267, 34);
            this.Input_Country.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Country.TabIndex = 10;
            this.Input_Country.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Country.TextMarginBottom = 0;
            this.Input_Country.TextMarginLeft = 3;
            this.Input_Country.TextMarginTop = 0;
            this.Input_Country.TextPlaceholder = "Country";
            this.Input_Country.UseSystemPasswordChar = false;
            this.Input_Country.WordWrap = true;
            // 
            // Input_City
            // 
            this.Input_City.AcceptsReturn = false;
            this.Input_City.AcceptsTab = false;
            this.Input_City.AnimationSpeed = 200;
            this.Input_City.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_City.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_City.BackColor = System.Drawing.Color.White;
            this.Input_City.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_City.BackgroundImage")));
            this.Input_City.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_City.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_City.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_City.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_City.BorderRadius = 6;
            this.Input_City.BorderThickness = 1;
            this.Input_City.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_City.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_City.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_City.DefaultText = "";
            this.Input_City.FillColor = System.Drawing.Color.White;
            this.Input_City.HideSelection = true;
            this.Input_City.IconLeft = null;
            this.Input_City.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_City.IconPadding = 10;
            this.Input_City.IconRight = null;
            this.Input_City.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_City.Lines = new string[0];
            this.Input_City.Location = new System.Drawing.Point(28, 178);
            this.Input_City.Margin = new System.Windows.Forms.Padding(2);
            this.Input_City.MaxLength = 32767;
            this.Input_City.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_City.Modified = false;
            this.Input_City.Multiline = false;
            this.Input_City.Name = "Input_City";
            stateProperties129.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties129.FillColor = System.Drawing.Color.Empty;
            stateProperties129.ForeColor = System.Drawing.Color.Empty;
            stateProperties129.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_City.OnActiveState = stateProperties129;
            stateProperties130.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties130.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties130.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties130.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_City.OnDisabledState = stateProperties130;
            stateProperties131.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties131.FillColor = System.Drawing.Color.Empty;
            stateProperties131.ForeColor = System.Drawing.Color.Empty;
            stateProperties131.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_City.OnHoverState = stateProperties131;
            stateProperties132.BorderColor = System.Drawing.Color.Silver;
            stateProperties132.FillColor = System.Drawing.Color.White;
            stateProperties132.ForeColor = System.Drawing.Color.Empty;
            stateProperties132.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_City.OnIdleState = stateProperties132;
            this.Input_City.Padding = new System.Windows.Forms.Padding(2);
            this.Input_City.PasswordChar = '\0';
            this.Input_City.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_City.PlaceholderText = "City";
            this.Input_City.ReadOnly = false;
            this.Input_City.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_City.SelectedText = "";
            this.Input_City.SelectionLength = 0;
            this.Input_City.SelectionStart = 0;
            this.Input_City.ShortcutsEnabled = true;
            this.Input_City.Size = new System.Drawing.Size(330, 34);
            this.Input_City.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_City.TabIndex = 9;
            this.Input_City.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_City.TextMarginBottom = 0;
            this.Input_City.TextMarginLeft = 3;
            this.Input_City.TextMarginTop = 0;
            this.Input_City.TextPlaceholder = "City";
            this.Input_City.UseSystemPasswordChar = false;
            this.Input_City.WordWrap = true;
            // 
            // Input_Address
            // 
            this.Input_Address.AcceptsReturn = false;
            this.Input_Address.AcceptsTab = false;
            this.Input_Address.AnimationSpeed = 200;
            this.Input_Address.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Address.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Address.BackColor = System.Drawing.Color.White;
            this.Input_Address.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Address.BackgroundImage")));
            this.Input_Address.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Address.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Address.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Address.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Address.BorderRadius = 6;
            this.Input_Address.BorderThickness = 1;
            this.Input_Address.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Address.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Address.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Address.DefaultText = "";
            this.Input_Address.FillColor = System.Drawing.Color.White;
            this.Input_Address.HideSelection = true;
            this.Input_Address.IconLeft = null;
            this.Input_Address.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Address.IconPadding = 10;
            this.Input_Address.IconRight = null;
            this.Input_Address.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Address.Lines = new string[0];
            this.Input_Address.Location = new System.Drawing.Point(28, 124);
            this.Input_Address.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Address.MaxLength = 32767;
            this.Input_Address.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Address.Modified = false;
            this.Input_Address.Multiline = false;
            this.Input_Address.Name = "Input_Address";
            stateProperties133.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties133.FillColor = System.Drawing.Color.Empty;
            stateProperties133.ForeColor = System.Drawing.Color.Empty;
            stateProperties133.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Address.OnActiveState = stateProperties133;
            stateProperties134.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties134.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties134.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties134.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Address.OnDisabledState = stateProperties134;
            stateProperties135.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties135.FillColor = System.Drawing.Color.Empty;
            stateProperties135.ForeColor = System.Drawing.Color.Empty;
            stateProperties135.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Address.OnHoverState = stateProperties135;
            stateProperties136.BorderColor = System.Drawing.Color.Silver;
            stateProperties136.FillColor = System.Drawing.Color.White;
            stateProperties136.ForeColor = System.Drawing.Color.Empty;
            stateProperties136.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Address.OnIdleState = stateProperties136;
            this.Input_Address.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Address.PasswordChar = '\0';
            this.Input_Address.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Address.PlaceholderText = "Address";
            this.Input_Address.ReadOnly = false;
            this.Input_Address.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Address.SelectedText = "";
            this.Input_Address.SelectionLength = 0;
            this.Input_Address.SelectionStart = 0;
            this.Input_Address.ShortcutsEnabled = true;
            this.Input_Address.Size = new System.Drawing.Size(620, 34);
            this.Input_Address.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Address.TabIndex = 8;
            this.Input_Address.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Address.TextMarginBottom = 0;
            this.Input_Address.TextMarginLeft = 3;
            this.Input_Address.TextMarginTop = 0;
            this.Input_Address.TextPlaceholder = "Address";
            this.Input_Address.UseSystemPasswordChar = false;
            this.Input_Address.WordWrap = true;
            // 
            // Input_Password
            // 
            this.Input_Password.AcceptsReturn = false;
            this.Input_Password.AcceptsTab = false;
            this.Input_Password.AnimationSpeed = 200;
            this.Input_Password.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Password.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Password.BackColor = System.Drawing.Color.White;
            this.Input_Password.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Password.BackgroundImage")));
            this.Input_Password.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Password.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Password.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Password.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Password.BorderRadius = 6;
            this.Input_Password.BorderThickness = 1;
            this.Input_Password.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Password.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Password.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Password.DefaultText = "";
            this.Input_Password.FillColor = System.Drawing.Color.White;
            this.Input_Password.HideSelection = true;
            this.Input_Password.IconLeft = null;
            this.Input_Password.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Password.IconPadding = 10;
            this.Input_Password.IconRight = null;
            this.Input_Password.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Password.Lines = new string[0];
            this.Input_Password.Location = new System.Drawing.Point(381, 66);
            this.Input_Password.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Password.MaxLength = 32767;
            this.Input_Password.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Password.Modified = false;
            this.Input_Password.Multiline = false;
            this.Input_Password.Name = "Input_Password";
            stateProperties137.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties137.FillColor = System.Drawing.Color.Empty;
            stateProperties137.ForeColor = System.Drawing.Color.Empty;
            stateProperties137.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Password.OnActiveState = stateProperties137;
            stateProperties138.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties138.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties138.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties138.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Password.OnDisabledState = stateProperties138;
            stateProperties139.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties139.FillColor = System.Drawing.Color.Empty;
            stateProperties139.ForeColor = System.Drawing.Color.Empty;
            stateProperties139.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Password.OnHoverState = stateProperties139;
            stateProperties140.BorderColor = System.Drawing.Color.Silver;
            stateProperties140.FillColor = System.Drawing.Color.White;
            stateProperties140.ForeColor = System.Drawing.Color.Empty;
            stateProperties140.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Password.OnIdleState = stateProperties140;
            this.Input_Password.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Password.PasswordChar = '\0';
            this.Input_Password.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Password.PlaceholderText = "Password";
            this.Input_Password.ReadOnly = false;
            this.Input_Password.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Password.SelectedText = "";
            this.Input_Password.SelectionLength = 0;
            this.Input_Password.SelectionStart = 0;
            this.Input_Password.ShortcutsEnabled = true;
            this.Input_Password.Size = new System.Drawing.Size(267, 34);
            this.Input_Password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Password.TabIndex = 7;
            this.Input_Password.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Password.TextMarginBottom = 0;
            this.Input_Password.TextMarginLeft = 3;
            this.Input_Password.TextMarginTop = 0;
            this.Input_Password.TextPlaceholder = "Password";
            this.Input_Password.UseSystemPasswordChar = false;
            this.Input_Password.WordWrap = true;
            // 
            // Input_Email
            // 
            this.Input_Email.AcceptsReturn = false;
            this.Input_Email.AcceptsTab = false;
            this.Input_Email.AnimationSpeed = 200;
            this.Input_Email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Input_Email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Input_Email.BackColor = System.Drawing.Color.White;
            this.Input_Email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Input_Email.BackgroundImage")));
            this.Input_Email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Input_Email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Input_Email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Input_Email.BorderColorIdle = System.Drawing.Color.Silver;
            this.Input_Email.BorderRadius = 6;
            this.Input_Email.BorderThickness = 1;
            this.Input_Email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Input_Email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Email.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Input_Email.DefaultText = "";
            this.Input_Email.FillColor = System.Drawing.Color.White;
            this.Input_Email.HideSelection = true;
            this.Input_Email.IconLeft = null;
            this.Input_Email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Email.IconPadding = 10;
            this.Input_Email.IconRight = null;
            this.Input_Email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Input_Email.Lines = new string[0];
            this.Input_Email.Location = new System.Drawing.Point(28, 66);
            this.Input_Email.Margin = new System.Windows.Forms.Padding(2);
            this.Input_Email.MaxLength = 32767;
            this.Input_Email.MinimumSize = new System.Drawing.Size(1, 1);
            this.Input_Email.Modified = false;
            this.Input_Email.Multiline = false;
            this.Input_Email.Name = "Input_Email";
            stateProperties141.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties141.FillColor = System.Drawing.Color.Empty;
            stateProperties141.ForeColor = System.Drawing.Color.Empty;
            stateProperties141.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Email.OnActiveState = stateProperties141;
            stateProperties142.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties142.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties142.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties142.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Input_Email.OnDisabledState = stateProperties142;
            stateProperties143.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties143.FillColor = System.Drawing.Color.Empty;
            stateProperties143.ForeColor = System.Drawing.Color.Empty;
            stateProperties143.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Email.OnHoverState = stateProperties143;
            stateProperties144.BorderColor = System.Drawing.Color.Silver;
            stateProperties144.FillColor = System.Drawing.Color.White;
            stateProperties144.ForeColor = System.Drawing.Color.Empty;
            stateProperties144.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Input_Email.OnIdleState = stateProperties144;
            this.Input_Email.Padding = new System.Windows.Forms.Padding(2);
            this.Input_Email.PasswordChar = '\0';
            this.Input_Email.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Input_Email.PlaceholderText = "Email";
            this.Input_Email.ReadOnly = false;
            this.Input_Email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Input_Email.SelectedText = "";
            this.Input_Email.SelectionLength = 0;
            this.Input_Email.SelectionStart = 0;
            this.Input_Email.ShortcutsEnabled = true;
            this.Input_Email.Size = new System.Drawing.Size(330, 34);
            this.Input_Email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Input_Email.TabIndex = 6;
            this.Input_Email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Input_Email.TextMarginBottom = 0;
            this.Input_Email.TextMarginLeft = 3;
            this.Input_Email.TextMarginTop = 0;
            this.Input_Email.TextPlaceholder = "Email";
            this.Input_Email.UseSystemPasswordChar = false;
            this.Input_Email.WordWrap = true;
            // 
            // lbl_otherinfo
            // 
            this.lbl_otherinfo.AllowParentOverrides = false;
            this.lbl_otherinfo.AutoEllipsis = false;
            this.lbl_otherinfo.CursorType = null;
            this.lbl_otherinfo.Font = new System.Drawing.Font("Ebrima", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_otherinfo.ForeColor = System.Drawing.SystemColors.ButtonShadow;
            this.lbl_otherinfo.Location = new System.Drawing.Point(28, 27);
            this.lbl_otherinfo.Name = "lbl_otherinfo";
            this.lbl_otherinfo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_otherinfo.Size = new System.Drawing.Size(129, 20);
            this.lbl_otherinfo.TabIndex = 5;
            this.lbl_otherinfo.Text = "Other Information";
            this.lbl_otherinfo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_otherinfo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // guna2CircleButton3
            // 
            this.guna2CircleButton3.BorderStyle = System.Drawing.Drawing2D.DashStyle.Dot;
            this.guna2CircleButton3.CheckedState.Parent = this.guna2CircleButton3;
            this.guna2CircleButton3.CustomImages.Parent = this.guna2CircleButton3;
            this.guna2CircleButton3.FillColor = System.Drawing.Color.MediumSeaGreen;
            this.guna2CircleButton3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.guna2CircleButton3.ForeColor = System.Drawing.Color.White;
            this.guna2CircleButton3.HoverState.FillColor = System.Drawing.Color.Red;
            this.guna2CircleButton3.HoverState.Parent = this.guna2CircleButton3;
            this.guna2CircleButton3.Location = new System.Drawing.Point(978, 8);
            this.guna2CircleButton3.Name = "guna2CircleButton3";
            this.guna2CircleButton3.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.guna2CircleButton3.ShadowDecoration.Parent = this.guna2CircleButton3;
            this.guna2CircleButton3.Size = new System.Drawing.Size(18, 19);
            this.guna2CircleButton3.TabIndex = 18;
            // 
            // guna2CircleButton2
            // 
            this.guna2CircleButton2.BorderStyle = System.Drawing.Drawing2D.DashStyle.Dot;
            this.guna2CircleButton2.CheckedState.Parent = this.guna2CircleButton2;
            this.guna2CircleButton2.CustomImages.Parent = this.guna2CircleButton2;
            this.guna2CircleButton2.FillColor = System.Drawing.Color.DarkOrange;
            this.guna2CircleButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.guna2CircleButton2.ForeColor = System.Drawing.Color.White;
            this.guna2CircleButton2.HoverState.FillColor = System.Drawing.Color.Red;
            this.guna2CircleButton2.HoverState.Parent = this.guna2CircleButton2;
            this.guna2CircleButton2.Location = new System.Drawing.Point(1002, 8);
            this.guna2CircleButton2.Name = "guna2CircleButton2";
            this.guna2CircleButton2.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.guna2CircleButton2.ShadowDecoration.Parent = this.guna2CircleButton2;
            this.guna2CircleButton2.Size = new System.Drawing.Size(18, 19);
            this.guna2CircleButton2.TabIndex = 17;
            // 
            // btn_Close
            // 
            this.btn_Close.BorderStyle = System.Drawing.Drawing2D.DashStyle.Dot;
            this.btn_Close.CheckedState.Parent = this.btn_Close;
            this.btn_Close.CustomImages.Parent = this.btn_Close;
            this.btn_Close.FillColor = System.Drawing.Color.Crimson;
            this.btn_Close.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_Close.ForeColor = System.Drawing.Color.White;
            this.btn_Close.HoverState.FillColor = System.Drawing.Color.Red;
            this.btn_Close.HoverState.Parent = this.btn_Close;
            this.btn_Close.Location = new System.Drawing.Point(1026, 8);
            this.btn_Close.Name = "btn_Close";
            this.btn_Close.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.btn_Close.ShadowDecoration.Parent = this.btn_Close;
            this.btn_Close.Size = new System.Drawing.Size(18, 19);
            this.btn_Close.TabIndex = 16;
            this.btn_Close.Click += new System.EventHandler(this.btn_Close_Click);
            // 
            // SignUpCustomer
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1060, 566);
            this.Controls.Add(this.guna2CircleButton3);
            this.Controls.Add(this.guna2CircleButton2);
            this.Controls.Add(this.btn_Close);
            this.Controls.Add(this.bunifuShadowPanel3);
            this.Controls.Add(this.bunifuShadowPanel2);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "SignUpCustomer";
            this.Text = "Form2";
            this.Load += new System.EventHandler(this.SignUpCustomer_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.bunifuShadowPanel3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox Input_FirstName;
        private Bunifu.UI.WinForms.BunifuLabel lbl_BioInfo;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox Input_PhoneNum;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Age;
        private Bunifu.UI.WinForms.BunifuTextBox Input_LastName;
        public Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_SignUp;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Cancel;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuRadioButton btn_Undertaking;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Country;
        private Bunifu.UI.WinForms.BunifuTextBox Input_City;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Address;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Password;
        private Bunifu.UI.WinForms.BunifuTextBox Input_Email;
        private Bunifu.UI.WinForms.BunifuLabel lbl_otherinfo;
        private Guna.UI2.WinForms.Guna2CircleButton guna2CircleButton3;
        private Guna.UI2.WinForms.Guna2CircleButton guna2CircleButton2;
        private Guna.UI2.WinForms.Guna2CircleButton btn_Close;
    }
}